const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting script...');

const translations = {
  601: "No tengo ganas. / No estoy de humor.",
  602: "No lo puedo evitar. / Qué le voy a hacer.",
  603: "Cuantos más, mejor. / Mientras más seamos, mejor.",
  604: "Yo me encargo. / Déjamelo a mí.",
  605: "Soy todo oídos. / Te escucho.",
  606: "No veo la hora. / Estoy que me muero de ganas.",
  607: "Por poco. / Fue por los pelos.",
  608: "Aquí tienes. / Eso es, exacto.",
  609: "Estás ladrando al árbol equivocado. / Te equivocas de persona.",
  610: "Allá vamos. / Aquí vamos de nuevo.",
  611: "Lo antes posible. / Cuanto antes.",
  612: "Ni idea. / No tengo la menor idea.",
  613: "No es lo mío. / No me va.",
  614: "Vayamos al grano. / Al punto.",
  615: "Voy tarde. / Se me está haciendo tarde.",
  616: "Se me fue de la cabeza. / Se me olvidó.",
  617: "Me muero de hambre. / Estoy famélico.",
  618: "Estoy lleno. / No me cabe nada más.",
  619: "Vamos a picar algo. / Comamos algo rápido.",
  620: "Vale la pena esperar. / Merece la espera.",
  621: "Dame un respiro. / Venga ya.",
  622: "Ni de broma. / Imposible.",
  623: "Depende. / Según.",
  624: "Nunca se sabe. / Quién sabe.",
  625: "Te aviso. / Te lo hago saber.",
  626: "Espero que sirva. / Ojalá ayude.",
  627: "Te lo agradezco. / Muy amable.",
  628: "Ese es el plan. / Esa es la idea.",
  629: "El tiempo lo dirá. / Ya veremos.",
  630: "Merece la pena intentarlo. / No pierdes nada.",
  631: "Todo el paquete. / La cosa completa.",
  632: "Empecemos. / Manos a la obra.",
  633: "Ahora que lo mencionas... / Eso me recuerda...",
  634: "Te contacto luego. / Luego hablamos.",
  635: "Mantenme al tanto. / Avísame.",
  636: "Dime. / Hazme saber.",
  637: "Sin duda alguna. / Está clarísimo.",
  638: "Jajaja. / Me parto.",
  639: "¡Dios mío! / ¡No me digas!",
  640: "Ya vuelvo. / Ahora regreso.",
  641: "Hablamos luego. / Nos vemos.",
  642: "Lo clavé. / Perfecto.",
  643: "No sé. / Ni idea.",
  644: "Para tu información. / Por si acaso.",
  645: "Mi error. / Culpa mía.",
  646: "Qué mala suerte. / Qué fastidio.",
  647: "Continuación. / Sigue.",
  648: "Pan comido. / Facilísimo.",
  649: "Igual yo. / Lo mismo digo.",
  650: "Te escucho. / Atento.",
  651: "Ánimo. / Arriba ese ánimo.",
  652: "Torpe. / Manazas.",
  653: "Mantengo mi postura. / No cambio de opinión.",
  654: "Tomar atajos. / Hacer las cosas a medias.",
  655: "No lo menciones. / Ni lo nombres.",
  656: "Estoy al límite. / Estoy muy nervioso.",
  657: "Andar con pies de plomo. / Ir con mucho cuidado.",
  658: "Apagarse. / Desvanecerse.",
  659: "Distanciarse. / Alejarse.",
  660: "Precisamente tú. / Tú de todos.",
  661: "Ya lo tengo hecho. / Me adelanté.",
  662: "¿Qué casualidad, no? / Qué coincidencia.",
  663: "Puntual. / Que respeta el tiempo.",
  664: "Olvida eso. / Borra lo dicho.",
  665: "No capta indirectas. / No pilla.",
  666: "Por si sirve de algo. / Aunque no valga mucho.",
  667: "Contestar mal. / Saltar.",
  668: "Ponerme en un aprieto. / Comprometerme.",
  669: "Comida reconfortante. / Comida del alma.",
  670: "Invito yo. / Pago yo.",
  671: "Dividir la cuenta. / A pachas.",
  672: "Exclusivo. / De grupito cerrado.",
  673: "Caballa curada. / Caballa en salazón.",
  674: "Dormir hasta tarde. / Quedarse en la cama.",
  675: "Me quedé dormido. / Pegué un trasnocho.",
  676: "Subestimar. / Infravalorar.",
  677: "Crédulo. / Fácil de engañar.",
  678: "Molesto / Irritado / Harto.",
  679: "Cabrear / Estar resentido.",
  680: "Disculparse no basta. / Perdón no es suficiente.",
  681: "Ya es toda una señorita. / Ha crecido mucho.",
  682: "Con pinzas. / No te lo creas todo.",
  683: "Pensando en voz alta. / Solo digo lo que pienso.",
  684: "Ídem. / Yo también.",
  685: "Esto no era lo que esperaba. / No me apunté para esto.",
  686: "No sirvo para esto. / No es para mí.",
  687: "Qué pena. / Qué bajón.",
  688: "Sacarme de quicio. / Ponerme de los nervios.",
  689: "Dame algo de crédito. / Reconóceme un poco.",
  690: "Terminar en una situación. / Acabar metido en.",
  691: "Si alguna vez te apetece... / Por si quieres...",
  692: "Mantener todo en orden. / Que no se descarrile.",
  693: "Deja de quejarte / No exageres / Llora todo lo que quieras.",
  694: "Yo asumo la responsabilidad. / Yo cargo con las culpas.",
  695: "Estoy entre la espada y la pared. / No sé qué elegir.",
  696: "Consultarlo con la almohada. / Pensarlo con calma.",
  697: "Qué atrevido. / Tienes cara.",
  698: "Guárdatelo. / No lo cuentes.",
  699: "El que sabe, sabe. / Los que pillan, pillan.",
  700: "Solo estoy mirando. / Echando un vistazo.",
  701: "Cuida tu boca. / Modera el lenguaje.",
  702: "Acobardarse. / Echarse atrás.",
  703: "Son cosas distintas. / No se pueden comparar.",
  704: "Búscate una vida. / Haz algo productivo.",
  705: "No le des vueltas / Pasa página / Déjalo ir.",
  706: "La gente no cambia. / Las personas son así.",
  707: "Eso me encanta. / Es lo que más me gusta.",
  708: "Vivir a través de otros. / Satisfacción indirecta.",
  709: "¿Cuánto es? / ¿Qué tal el golpe?",
  710: "Nací así. / Soy así de nacimiento.",
  711: "Lo esencial es... / En resumen...",
  712: "No busques problemas. / No provoques.",
  713: "Veamos qué pasa. / A ver cómo sale.",
  714: "Decisión obvia. / Ni pensarlo.",
  715: "Ahora que lo pienso... / Pensándolo bien...",
  716: "Habla bien de mí. / Recomiéndame.",
  717: "Estoy agotado. / Estoy hecho polvo.",
  718: "Me pisoteó. / Me trató fatal.",
  719: "No seas tan duro contigo. / No te machaques.",
  720: "Se pone de mal humor cuando tiene hambre. / El hambre le cambia.",
  721: "Se me acaba de ocurrir. / Me vino a la mente.",
  722: "Las piernas largas vienen de familia. / Es genético.",
  723: "De tal palo, tal astilla. / Hijo de tigre sale pintado.",
  724: "De la nada. / Sin previo aviso.",
  725: "De Pascuas a Ramos. / Muy de vez en cuando.",
  726: "Tiene el descaro de aparecer. / Qué cara tiene.",
  727: "Dicho esto, ten cuidado. / Aun así, ojo.",
  728: "Me da escalofríos. / Me pone los pelos de punta.",
  729: "Suena poco creíble. / Parece exagerado.",
  730: "Estoy a punto de comprarlo. / Casi lo compro.",
  731: "¿Por quién me tomas? / ¿Qué te crees?",
  732: "Me dejé llevar. / Me pasé de la raya.",
  733: "No soy de arrepentirme. / No me gusta lamentarme.",
  734: "Por un oído y por el otro. / No hace caso.",
  735: "Dame tu mejor precio. / Tu oferta más baja.",
  736: "No nací ayer. / No soy tonto.",
  737: "Lo dejamos para otro día. / Posponemos.",
  738: "Ahí va otra vez. / Ya empezó de nuevo.",
  739: "Esa es mi opinión. / Mi granito de arena.",
  740: "Escúchame bien / Presta atención.",
  741: "No me lo esperaba. / Me pilló por sorpresa.",
  742: "Soy joven de espíritu. / Tengo alma joven.",
  743: "No puedo quitarme esta sensación. / Me persigue el presentimiento.",
  744: "Lee el ambiente. / Capta la onda.",
  745: "Lo recomiendo al 100%. / No puedo recomendarlo más.",
  746: "Darse cuenta / Captar la indirecta / Pillar la onda.",
  747: "Utensilios de cocina. / Menaje.",
  748: "Parlanchín. / Cotorra.",
  749: "Más o menos. / Aproximadamente.",
  750: "Congeniar. / Hacer buenas migas.",
  751: "Es un partidazo. / Es un buen partido.",
  752: "Tragarte el orgullo. / Humillarte.",
  753: "Volverse loco. / Flipar.",
  754: "Reservado. / Hermético.",
  755: "Lo primero es lo primero. / Prioridades.",
  756: "Mejor amigo. / Amigo del alma.",
  757: "Día malo. / Día de bajón.",
  758: "Arrepentimiento del comprador. / Remordimiento post-compra.",
  759: "Ya que estamos. / De paso.",
  760: "Disfruta la vida. / Relájate un poco.",
  761: "Está tirado de precio. / Es una ganga.",
  762: "Tiene potencial. / Promete.",
  763: "Tomar con filosofía. / No darle importancia.",
  764: "Estoy en ello. / Trabajando en eso.",
  765: "Déjame pensarlo. / Lo considero.",
  766: "Está en juego. / Está en riesgo.",
  767: "Punto muerto. / Estancamiento.",
  768: "Dar marcha atrás. / Retractarse.",
  769: "Hacer las paces. / Reconciliarse.",
  770: "Dar el primer paso. / Tomar la iniciativa.",
  771: "Llegar a un acuerdo. / Ponerse de acuerdo.",
  772: "Romper el silencio. / Hablar primero.",
  773: "Dejar atrás. / Superar.",
  774: "Seguir adelante. / Continuar.",
  775: "Dar vuelta a la página. / Empezar de nuevo.",
  776: "Cerrar el capítulo. / Terminar con eso.",
  777: "Abrir un nuevo capítulo. / Comenzar algo nuevo.",
  778: "Tomar un descanso. / Hacer una pausa.",
  779: "Recargar pilas. / Recuperar energía.",
  780: "Desconectar. / Relajarse.",
  781: "Tomárselo con calma. / Sin prisa.",
  782: "Paso a paso. / Poco a poco.",
  783: "Roma no se construyó en un día. / Las cosas llevan tiempo.",
  784: "La práctica hace al maestro. / Practicando se aprende.",
  785: "Nunca es tarde para aprender. / Siempre se puede aprender.",
  786: "Cada día se aprende algo nuevo. / Aprendizaje continuo.",
  787: "El conocimiento es poder. / Saber es poder.",
  788: "La experiencia es la mejor maestra. / Se aprende de los errores.",
  789: "Vivir y aprender. / Aprender de la vida.",
  790: "Cometer errores es humano. / Todos nos equivocamos.",
  791: "Nadie es perfecto. / Todos tenemos defectos.",
  792: "Errar es de humanos. / Los errores son normales.",
  793: "Aprender de los errores. / Crecer con las equivocaciones.",
  794: "No hay mal que por bien no venga. / Todo tiene su lado positivo.",
  795: "Después de la tormenta viene la calma. / Todo pasa.",
  796: "Al mal tiempo, buena cara. / Mantener el ánimo.",
  797: "No hay que llorar sobre la leche derramada. / Lo hecho, hecho está.",
  798: "Más vale prevenir que lamentar. / Mejor prevenir.",
  799: "Más vale tarde que nunca. / Mejor tarde.",
  800: "Nunca digas nunca. / Todo es posible."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
