const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';
const data = JSON.parse(fs.readFileSync(path, 'utf8'));

const batch = {
  1: "彼は3つ年上でした。(kare wa mittsu toshiue deshita)",
  2: "彼女は3つ年下でした。(kanojo wa mittsu toshishita deshita)",
  3: "全然違う。(zenzen chigau) / 的外れだよ。(matohazure da yo)",
  4: "席とっといて。(seki tottoite)",
  5: "平飼い卵。(hiragai tamago)",
  6: "直感でわかる。(chokkan de wakaru) / なんとなくそんな気がする。(nantonaku sonna ki ga suru)",
  7: "お節介な人。(osekkai na hito) / 出しゃばり。(deshabari)",
  8: "彼女の彼氏の話はさせないで。(kanojo no kareshi no hanashi wa sasenaide) / その話はしたくない。(sono hanashi wa shitakunai)",
  9: "仕方がない。(shikata ga nai) / しょうがない。(shouganai)",
  10: "必要に迫られて。(hitsuyou ni semararete) / やむを得ず。(yamu o ezu)",
  11: "他に選択肢がない。(hoka ni sentakushi ga nai) / こうするしかなかった。(kou suru shika nakatta)",
  12: "あなたがその話題を出したから。(anata ga sono wadai o dashita kara) / 言われてみれば。(iwarete mireba)",
  13: "ただ惰性でやってるだけ。(tada dasei de yatteru dake) / ただこなしてるだけ。(tada konashiteru dake)",
  14: "私はあまり後悔しないタイプだ。(watashi wa amari koukai shinai taipu da)",
  15: "回転寿司。(kaitenzushi)",
  16: "パクチー。(pakuchii)",
  17: "突然。(totsuzen) / 藪から棒に。(yabu kara bou ni)",
  18: "邪魔しないようにするね。(jama shinai you ni suru ne) / そろそろ失礼するね。(sorosoro shitsurei suru ne)",
  19: "〜に大きな拍手を送る。(~ ni ookina hakushu o okuru)",
  20: "話したいことがあるんだ。(hanashitai koto ga arunda)",
  21: "あなたが言えた義理？(anata ga ieta giri?) / よく言うよ。(yoku iu yo)",
  22: "行く前に誤解を解いておこう。(iku mae ni gokai o toite okou)",
  23: "ただ言ってみただけ。(tada itte mita dake)",
  24: "私は気分屋です。(watashi wa kibunya desu)",
  25: "暴れる。(abareru) / 調子が悪い。(choushi ga warui)",
  26: "本当に不便だ。(hontou ni fuben da) / タイミングが悪い。(taimingu ga warui)",
  27: "人生を謳歌する。(jinsei o ouka suru) / 精一杯生きる。(seiippai ikiru)",
  28: "食べ過ぎて動けない。(tabesugite ugokenai) / フードコマ。(fuudo koma)",
  29: "それはいい考えだね。(sore wa ii kangae da ne) / それで行こう。(sore de ikou)",
  30: "反射的な反応ではない。(hanshateki na hannou dewa nai) / よく考えた上でのことだ。(yoku kangaeta ue de no koto da)",
  31: "ただ形式的にやってるわけじゃない。(tada keishikiteki ni yatteru wake ja nai)",
  32: "本気だよ。(honki da yo) / まじだよ。(maji da yo)",
  33: "夕食に行く元気ある？(yuushoku ni iku genki aru?) / ご飯行く？(gohan iku?)",
  34: "そうできればいいんだけど。(sou dekireba ii ndakedo) / 残念だけど無理。(zannen dakedo muri)",
  35: "大切な人。(taisetsu na hito) / パートナー。(paatonaa)",
  36: "もちろん。(mochiron) / いいよ。(ii yo)",
  37: "任せて。(makasete) / わかった。(wakatta)",
  38: "はい、どうぞ。(hai, douzo)",
  39: "拍手喝采する。(hakushu kassai suru)",
  40: "私の言うことをよく聞いて。(watashi no iu koto o yoku kiite) / 絶対にない。(zettai ni nai)",
  41: "気持ちは若い。(kimochi wa wakai)",
  42: "悪化する。(akka suru) / 失敗する。(shippai suru)",
  43: "借りてきた猫みたいだね。(karitekita neko mitai da ne) / 以前より静かだね。(izen yori shizuka da ne)",
  44: "予感が拭えない。(yokan ga nuguenai) / 嫌な予感がする。(iya na yokan ga suru)",
  45: "超おすすめ。(chou osusume) / 絶対いいよ。(zettai ii yo)",
  46: "携帯をマナーモードにして。(keitai o manaa moudo ni shite)",
  47: "責任は私が取る。(sekinin wa watashi ga toru) / 私が責任者だ。(watashi ga sekininsha da)",
  48: "予約でいっぱいだ。(yoyaku de ippai da)",
  49: "今日の予定はびっしりだ。(kyou no yotei wa bisshiri da)",
  50: "予約で満杯だった。(yoyaku de manpai datta)",
  51: "近所の友達。(kinjo no tomodachi)",
  52: "気持ちは若いです。(kimochi wa wakai desu)",
  53: "聞いて。(kiite) / 質問して。(shitsumon shite)",
  54: "猿も木から落ちる。(saru mo ki kara ochiru) / 弘法にも筆の誤り。(koubou ni mo fude no ayamari)",
  55: "自分の足で稼ぐ。(jibun no ashi de kasegu) / 地道に回る。(jimichi ni mawaru)",
  56: "次は何？(tsugi wa nani?) / さてどうする？(sate dou suru?)",
  57: "私の出身はどこでしょう？ここは私たちの土地だ。(watashi no shusshin wa doko deshou? koko wa watashitachi no tochi da)",
  58: "狂ってる。(kurutteru) / バカげてる。(bakageteru)",
  59: "とんでもない。(tondemonai) / 法外な。(hougai na)",
  60: "それは認めるよ。(sore wa mitomeru yo) / 一理あるね。(ichiri aru ne)",
  61: "仕事に夢中になりすぎた。(shigoto ni muchuu ni narisugita) / 調子に乗りすぎた。(choushi ni norisugita)",
  62: "コーヒーが飲みたい。(kouhii ga nomitai)",
  63: "頭がパンクしそう。(atama ga panku shisou) / 疲れ果てた。(tsukarehateta)",
  64: "なんでわざわざ。(nande wazawaza) / するだけ無駄。(suru dake muda)",
  65: "くつろぐ。(kutsurogu) / リラックスする。(rirakkusu suru)",
  66: "聞いてよ。(kiite yo) / あのね。(ano ne)",
  67: "前もって。(maemotte) / 事前に。(jizen ni)",
  68: "強引すぎる。(gouin sugiru) / 押しが強すぎる。(oshi ga tsuyosugiru)",
  69: "感動した。(kandou shimashita) / 圧倒された。(attou sareta)",
  70: "最近迷惑かけてごめん。(saikin meiwaku kakete gomen)",
  71: "経験する。(keiken suru) / 通り抜ける。(toorinukeru)",
  72: "言うまでもない。(iu made mo nai) / 当然だ。(touzen da)",
  73: "〜というところが好き。(~ to iu tokoro ga suki)",
  74: "何が何でも。(nani ga nan demo) / どうあっても。(dou attemo)",
  75: "私の経験からすると。(watashi no keiken kara suru to)",
  76: "前言撤回する。(zengen tekkai suru) / 謝る。(ayamaru)",
  77: "期待通りだ。(kitai doori da)",
  78: "もっと食べたくなる。(motto tabetakunaru) / 病みつきになる。(yamitsuki ni naru)",
  79: "勝ち目はなかった。(kachime wa nakatta) / 最初から無理だった。(saisho kara muri datta)",
  80: "予想できたはずなのに。(yosou dekita hazu na noni)",
  81: "今日の気分はどう？(kyou no kibun wa dou?) / 調子どう？(choushi dou?)",
  82: "〜に腹を立てる。(~ ni hara o tateru) / 〜にムカつく。(~ ni mukatsuku)",
  83: "厳しく審査する。(kibishiku shinsa suru) / 入念に調べる。(nyuunen ni shiraberu)",
  84: "裏があるんでしょ？(ura ga aru ndesho?) / 条件は何？(jouken wa nani?)",
  85: "何もいらないよ。(nani mo iranai yo) / 気を使わないで。(ki o tsukawanaide)",
  86: "今、肩の治療を受けています。(ima, kata no chiryou o ukete imasu)",
  87: "つむじ。(tsumuji) / 頭のてっぺん。(atama no teppen)",
  88: "すごく迷ってる。(sugoku mayotteru) / 決められない。(kimerarenai)",
  89: "中途半端な状態。(chuutohanpa na joutai) / どっちつかず。(docchitsukazu)",
  90: "彼は本物だ。(kare wa honmono da) / 彼はすごい。(kare wa sugoi)",
  91: "彼はいい男だ。(kare wa ii otoko da) / 彼は逃したくない人だ。(kare wa nogashitakunai hito da)",
  92: "怒らないで。(okoranaide) / ヘソを曲げないで。(heso o magenaide)",
  93: "そんなに後悔していない。(sonna ni koukai shiteinai)",
  94: "中年の危機。(chuunen no kiki)",
  95: "大げさだよ。(oogesa da yo) / ドラマチックにしないで。(doramachikku ni shinaide)",
  96: "泣き言を言うな。(nakigoto o iu na)",
  97: "言葉を失う。(kotoba o ushinau) / 何と言っていいかわからない。(nan to itte ii ka wakaranai)",
  98: "今のわかった？(ima no wakatta?) / 理解できた？(rikai dekita?)",
  99: "空気を読むこと。(kuuki o yomu koto) / 社会的な合図。(shakaiteki na aizu)",
  100: "今の気づいた？(ima no kizuita?) / 今のわかった？(ima no wakatta?)"
};

data.forEach(item => {
  if (batch[item.id]) {
    item.japanese = batch[item.id];
  }
});

fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
console.log('Batch 1 (1-100) enriched with Japanese.');
