const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting script...');

const translations = {
  401: "Vale, vete. / Anda, vete ya.",
  402: "¿Por qué no fui capaz de decirlo? / ¿Qué me impidió decirlo?",
  403: "Come hasta hartarte. / Ponte las botas.",
  404: "Incierto. / En la cuerda floja.",
  405: "Me sentí muy agobiado. / Estaba muy preocupado.",
  406: "¿Qué dices? Me perdí. / ¿Cómo? No te sigo.",
  407: "Ojalá. / Ya quisiera yo.",
  408: "Ni lo sueñes. / Va a ser que no.",
  409: "La previa. / Beber antes de salir.",
  410: "Nacido y criado. / De aquí de toda la vida.",
  411: "Música para mis oídos. / Justo lo que quería oír.",
  412: "Ve al grano. / Déjate de rodeos.",
  413: "Voy a llegar 20 minutos tarde. / Se me ha hecho 20 minutos tarde.",
  414: "Me pillaron. / Me cazaron.",
  415: "Cuéntame cómo fue ese día. / Detállame ese día.",
  416: "¿Qué tramas? / ¿Cuál es la intención?",
  417: "Se le fue la olla. / Explotó (de ira).",
  418: "Cómplice. / Compinche.",
  419: "Ir a ver a alguien (generalmente hospital/cárcel) / Hacer una visita.",
  420: "No lo llevo encima. / No lo traigo conmigo.",
  421: "La cola empieza allí atrás. / La fila está allá.",
  422: "Cortar por lo sano. / Romper (relaciones).",
  423: "A lo grande o nada. / Si se hace, se hace bien.",
  424: "Fui un impulsivo. / Me precipité.",
  425: "Te ves demacrado. / Estás muy chupado (de cara).",
  426: "Cantar como un canario. / Desembuchar todo.",
  427: "Comerle a alguien la hacienda. / Dejar la despensa vacía.",
  428: "Le carcome por dentro. / Se lo llevan los demonios.",
  429: "Me lo imaginaba. / Era de esperar.",
  430: "Poner a alguien verde. / Soltarle de todo a alguien.",
  431: "De una forma u otra. / Sea como sea.",
  432: "Giros inesperados. / Idas y venidas.",
  433: "Recompensar generosamente. / Pagar muy bien.",
  434: "Hacer de tripas corazón. / Tragarse el sapo.",
  435: "A toda costa. / Cueste lo que cueste.",
  436: "Como un jarro de agua fría. / Inesperado totalmente.",
  437: "Desmoronándose. / Cayéndose a pedazos.",
  438: "Pensar con claridad. / Tener la cabeza en su sitio.",
  439: "Migraña. / Jaqueca.",
  440: "Dejar a alguien de lado. / Marginar.",
  441: "Yo qué sé. / Ni idea (no soy quien para saberlo).",
  442: "No te alteres. / No te pongas nervioso.",
  443: "¿Puedes subirlo a mi habitación? / ¿Lo llevas a mi cuarto?",
  444: "Tomaré lo mismo. / Lo mismo para mí.",
  445: "Llevo tiempo queriendo decirte... / Tenía ganas de decirte...",
  446: "¿Quieres otra? / ¿Te pongo otra?",
  447: "Compadecerse. / Entender lo que siente alguien.",
  448: "¿Cuánto tiempo ha pasado? / ¡Cuánto tiempo!",
  449: "¿Cómo te ha ido? / ¿Qué ha sido de ti?",
  450: "Caso atípico. / Excepción.",
  451: "Me vendría bien un poco. / Necesito algo de...",
  452: "Tener mano para... / Dársele bien...",
  453: "Tienes un don natural. / Naciste para esto.",
  454: "Tienes facilidad de palabra. / Qué labia tienes.",
  455: "Me salió natural. / No me costó nada aprenderlo.",
  456: "Tira una cifra. / Dímelo a ojo.",
  457: "Eres muy disciplinado. / Tienes mucha fuerza de voluntad.",
  458: "Me da escalofríos. / Me pone la piel de gallina.",
  459: "Cogí el hábito de... / Me acostumbré a...",
  460: "Déjame compensarte. / Deja que te lo pague de alguna forma.",
  461: "Me siento pocho. / Estoy indispuesto.",
  462: "Explotar (ira) / Petarlo (éxito) / Estallar.",
  463: "Inmejorable. / Mejor imposible.",
  464: "Dejarlo de golpe. / Cortar en seco.",
  465: "Legítimo / De verdad / Genial (jerga).",
  466: "No es rival para mí. / No me llega ni a la suela.",
  467: "Con calma. / Despacito y con buena letra.",
  468: "Oki doki. / Vale, hecho.",
  469: "Meh. / Ni fú ni fá.",
  470: "Tiene sentido. / Cuadra.",
  471: "La calidad del aire es mala. / Hay mucha contaminación.",
  472: "Tranquilote. / Un tío relajado.",
  473: "Esto servirá. / Con esto vale.",
  474: "Todo el tinglado. / El lote completo.",
  475: "Pan comido. / Chupado.",
  476: "Estar resentido. / Tener una espinita clavada.",
  477: "Actitud arisca. / Estar de uñas.",
  478: "Me lo dicen mucho. / Escucho eso a menudo.",
  479: "Sácala en vertical. / Haz la foto vertical.",
  480: "Troll. / Provocador en redes.",
  481: "Estoy flipando (mal). / Me está dando un ataque.",
  482: "¿Están abiertos hoy? / ¿Abrís hoy?",
  483: "Pasando una fase. / Es una etapa.",
  484: "Se le pasará con la edad. / Ya madurará.",
  485: "Audiencia / Público.",
  486: "Sanguijuela. / Chupasangre (persona).",
  487: "¡Hace un frío que pela! / ¡Está helando fuera!",
  488: "Da que pensar. / Sugerente.",
  489: "O sueltas prenda o te callas. / Canta o cierra el pico.",
  490: "Canceló el proyecto. / Suspendió el proyecto.",
  491: "Es mi día libre de dieta. / Hoy me salto la dieta.",
  492: "Me costó dormir. / Tuve problemas para conciliar el sueño.",
  493: "Me lo pasé bomba. / Fue la caña.",
  494: "Ni idea. / No sepa.",
  495: "Las chicas... / Cosas de chicas...",
  496: "Invito yo. / Corre de mi cuenta.",
  497: "Hace calor para noviembre. / Está templado para ser noviembre.",
  498: "Está bien para el precio que tiene. / Buena relación calidad-precio.",
  499: "Solo pensaba en voz alta. / Era un comentario al aire.",
  500: "No le des tanta importancia. / No busques segundas intenciones.",
  501: "Considerar una idea. / Barajar una posibilidad.",
  502: "Rentable. / Lo que más cunde por tu dinero.",
  503: "Esta expectación es una locura. / Se está caldeando el ambiente que no veas.",
  504: "Dime qué piensas. / ¿En qué piensas?",
  505: "Alterarse. / Ponerse nervioso.",
  506: "¿Cuál es la prisa? / ¿Por qué corres tanto?",
  507: "¿A qué esperamos? / ¿Cuál es el retraso?",
  508: "¡Lo conseguiste! / Te salió bien.",
  509: "Podría ser peor. / Menos mal.",
  510: "Dispara. / Suéltalo.",
  511: "Estoy comprometido con Polonia. / Tengo un compromiso con Polonia.",
  512: "El lado positivo es... / Lo bueno dentro de lo malo...",
  513: "Estoy en racha. / Voy lanzado.",
  514: "Ya he incluido tus sugerencias. / Ya metí tus cambios.",
  515: "Hacerse una paja. / Masturbarse (vulgar).",
  516: "Te va a marear. / Te va a tomar el pelo.",
  517: "Estoy por aquí. / Ando cerca.",
  518: "En mi opinión... / A mi parecer...",
  519: "Abrígate. / Mantente caliente.",
  520: "Fresquito y agradable. / Refrescante.",
  521: "Pisarle el terreno a alguien. / Inmiscuirse.",
  522: "Bebida de pie. / Copa rápida de pie.",
  523: "Dice mucho. / Es muy elocuente.",
  524: "Habla por sí solo. / No necesita explicación.",
  525: "Fue una ganga. / Un chollo.",
  526: "Deberíamos hacer acopio, está tirado de precio. / Hay que comprar bastante, es un regalo.",
  527: "¿Qué está bueno aquí? / ¿Qué recomiendas?",
  528: "Trazar gráficos. / Dibujar gráficas.",
  529: "Instalar paquetes. / Instalar librerías.",
  530: "Guardar imágenes. / Salvar fotos.",
  531: "Acceder a imágenes. / Ver fotos.",
  532: "Ni se me pasó por la cabeza. / Jamás se me ocurrió.",
  533: "Estar deshabilitado. / Desactivado.",
  534: "No funcionará. / No va a ir.",
  535: "No lo intentes. / Ni pruebes.",
  536: "Formato de salida deseado. / Cómo quieres el resultado.",
  537: "Tener prioridad. / Prevalecer.",
  538: "Ignorar las pautas. / Saltarse las normas.",
  539: "Encabezados claros y lógicos. / Títulos ordenados.",
  540: "Párrafos cortos. / Textos breves.",
  541: "Bloques de texto densos. / Ladrillos de texto.",
  542: "Viñetas. / Puntos.",
  543: "Condescendiente. / Altivo.",
  544: "Listas numeradas. / Enumeraciones.",
  545: "Puntos clave. / Conclusiones principales.",
  546: "Ideas agrupadas. / Conceptos juntos.",
  547: "Listas con viñetas. / Listas sin orden.",
  548: "Listas ordenadas. / Listas numéricas.",
  549: "Fluir lógicamente. / Tener coherencia.",
  550: "Escanear y entender puntos clave rápido. / Leer en diagonal y pillar lo básico.",
  551: "Legibilidad. / Facilidad de lectura.",
  552: "Conservar todas las citas. / Mantener las referencias.",
  553: "Incrustar citas. / Meter referencias.",
  554: "Paternalista / Tratar con superioridad",
  555: "Al principio de los párrafos. / Al empezar el párrafo.",
  556: "Mencionar las fuentes. / Citar el origen.",
  557: "Delante de los encabezados. / Antes de los títulos.",
  558: "¿Qué pasa? / ¿Qué hay?",
  559: "¡Cuánto tiempo! / Dichosos los ojos.",
  560: "No te preocupes. / Tranqui.",
  561: "Es lo que hay. / Ajo y agua.",
  562: "Ponte cómodo. / Estás en tu casa.",
  563: "Tómatelo con calma. / Relájate.",
  564: "Sigue así. / Buen trabajo.",
  565: "¡Buen provecho! / ¡Que aproveche!",
  566: "¡Salud! (estornudo) / Jesús.",
  567: "Cuídate. / Ve con cuidado.",
  568: "Estaré en contacto. / Te digo algo.",
  569: "Avísame. / Mantenme informado.",
  570: "¿Me echas una mano? / ¿Me ayudas?",
  571: "Me temo que no puedo. / Va a ser que no.",
  572: "Quizás en otra ocasión. / Lo dejamos para otra.",
  573: "De nada. / No hay de qué.",
  574: "¡Enhorabuena! / ¡Felicidades!",
  575: "Lo siento mucho. / Mi más sentido pésame (si es muerte) / Cuánto lo siento.",
  576: "¡Qué pena! / ¡Qué lástima!",
  577: "¿Cómo se dice...? / ¿Cómo se llama...?",
  578: "No lo pillo. / No entiendo.",
  579: "¿Podrías repetirlo? / ¿Otra vez, porfa?",
  580: "¡Es pan comido! / ¡Está tirado!",
  581: "Está lloviendo a cántaros. / Cae la del pulpo.",
  582: "Me muero de hambre. / Tengo un agujero en el estómago.",
  583: "Estoy reventado. / Estoy hecho polvo.",
  584: "Cuesta un ojo de la cara. / Vale un riñón.",
  585: "Tomar el pelo. / Quedarse con alguien.",
  586: "Estar en las mismas. / Ver las cosas igual.",
  587: "La gota que colma el vaso. / Ya no aguanto más.",
  588: "Hacer novillos / Salir temprano. / Escaquearse.",
  589: "Mejor tarde que nunca. / Más vale tarde.",
  590: "Romper el hielo. / Empezar la charla.",
  591: "Haz lo que quieras. / Como veas.",
  592: "Vamos a medias. / Pagamos a  pachas.",
  593: "Tocar madera. / Toco madera.",
  594: "¡Crucemos los dedos! / ¡Suerte!",
  595: "Se me fue. / Se me pasó.",
  596: "No me suena. / No me dice nada.",
  597: "Me lo quitas de la boca. / Iba a decir lo mismo.",
  598: "El mundo es un pañuelo. / ¡Qué pequeño es el mundo!",
  599: "Más vale prevenir que curar. / Hombre precavido vale por dos.",
  600: "Matar dos pájaros de un tiro. / Dos en uno."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
