const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting script...');

const translations = {
  201: "Terminar en una situación así. / Verme envuelto en esto.",
  202: "Echar un vistazo rápido. / Leer por encima.",
  203: "Que así sea. / Pues nada, allá él.",
  204: "Hechos el uno para el otro. / Son tal para cual.",
  205: "Lo que bien empieza, bien acaba. / Buen comienzo, mitad hecha.",
  206: "Hacerle la pelota a alguien. / Dorarle la píldora.",
  207: "Me la colaron con el anuncio. / Caí en la trampa del anuncio.",
  208: "¿Por casualidad...? / ¿De casualidad...?",
  209: "Tengo el estómago delicado. / Soy de estómago sensible.",
  210: "¡Fondo! / ¡Hidalgo!",
  211: "No me lo restregues. / No eches sal a la herida.",
  212: "Siente algo por ti. / Le gustas.",
  213: "Enamorarse de. / Caer en (un engaño).",
  214: "Dudoso. / No me fío mucho.",
  215: "¡Contemplad! / ¡Mirad esto!",
  216: "Lista del decano. / Cuadro de honor.",
  217: "No intentes engañarme. / No te pases de listo conmigo.",
  218: "Me gastaron una broma. / Caí en la inocentada.",
  219: "¡Písale! / ¡Dale caña!",
  220: "Cazafortunas. / Interesada/o.",
  221: "Eres puro bla bla bla. / Mucho ruido y pocas nueces.",
  222: "Estoy de acuerdo con eso. / Te apoyo en eso.",
  223: "Estoy hasta arriba. / No doy abasto.",
  224: "Un pequeño golpe. / Un choque leve.",
  225: "No puedo permitirme el lujo de vaguear. / No puedo dormirme en los laureles.",
  226: "Vamos viendo sobre la marcha. / Improvisemos.",
  227: "Mira quién habla. / Se cree el ladrón que todos son de su condición.",
  228: "De boca en boca. / Por el boca a boca.",
  229: "Tengo náuseas. / Me siento revuelto.",
  230: "Recuperar el aliento. / Tomar aire.",
  231: "Estrenando zapatos nuevos. / Domando los zapatos.",
  232: "Olvidarte de todo. / Despejar la mente.",
  233: "Hacer el vacío. / Ignorar a alguien fríamente.",
  234: "No me ofendo. / Tranquilo, no pasa nada.",
  235: "Debí haberlo pensado mejor. / Tendría que haberle dado una vuelta más.",
  236: "No quiero ser cotilla. / No quiero meterme donde no me llaman.",
  237: "Hacer un Tom Sawyer. / Engañar a alguien para que haga tu trabajo.",
  238: "Nada que perder. / No pierdo nada por intentar.",
  239: "Come más con los ojos que con la boca. / Se te llenaron los ojos antes que la barriga.",
  240: "Hablar es gratis. / Del dicho al hecho hay mucho trecho.",
  241: "El paquete completo. / Lo tiene todo.",
  242: "Sigue tu instinto. / Haz caso a tus tripas.",
  243: "Me late fuerte el corazón. / Tengo mariposas en el estómago.",
  244: "Los sentimientos se apagan. / Se enfrió la cosa.",
  245: "Deja de restregármelo. / Ya vale de recordármelo.",
  246: "Eso demuestra que... / Ahí se ve que...",
  247: "El poder de la mente. / Querer es poder.",
  248: "Intercambiar ideas contigo. / Rebotar ideas.",
  249: "Sentido de pertenencia. / Sentirse parte de algo.",
  250: "Mimarme. / Darme un capricho.",
  251: "Darme un gusto. / Consentirme.",
  252: "Está muy cutre. / Se ve muy dejado.",
  253: "No está nada mal. / Ni tan mal.",
  254: "Suena cursi. / Suena ñoño.",
  255: "Puede parecer obvio. / Sonará evidente, pero...",
  256: "Mira quién fue a hablar. / Dijo la sartén al cazo.",
  257: "Voy pillado de tiempo. / Ando justo de tiempo.",
  258: "Cuestión de tiempo. / Es solo esperar.",
  259: "El tiempo corre. / Tic tac, tic tac.",
  260: "Tu mejor opción. / Lo más seguro es...",
  261: "No soy yo hoy. / Hoy no estoy católico.",
  262: "Espabila. / Aclárate las ideas.",
  263: "Baja de las nubes. / Pon los pies en la tierra.",
  264: "Las fechas límite se echan encima. / Los plazos aprietan.",
  265: "Haciendo malabares con todo. / Estoy a mil cosas.",
  266: "Amante de la naturaleza de aire libre. / Muy de campo/montaña.",
  267: "¿Pillas por dónde voy? / ¿Me sigues?",
  268: "Reunión familiar. / Evento familiar.",
  269: "Hazte un hueco. / Córrete un poco.",
  270: "Mantén la compostura. / No te desmorones.",
  271: "Mantén la calma. / No pierdas los papeles.",
  272: "Hace un día precioso. / Está buenísimo fuera.",
  273: "No te lo tengas tan creído. / No te flipes.",
  274: "Deja de darme la lata. / No me chinhes más.",
  275: "Tú mismo. / Date el gusto.",
  276: "Consultarlo contigo. / Comentártelo antes.",
  277: "Redactando. / Haciendo el borrador.",
  278: "Viene a ser lo mismo. / Tanto monta, monta tanto.",
  279: "No montes un numerito. / No hagas una escena.",
  280: "No la pagues conmigo. / Yo no tengo la culpa.",
  281: "Qué rencoroso. / Qué quisquilloso.",
  282: "Vienen cosas buenas. / Lo mejor está por llegar.",
  283: "Lo estás petando. / Te estás saliendo.",
  284: "Lo has bordado. / La rompiste.",
  285: "Alucinante. / Te vuela la cabeza.",
  286: "Felpudo. / Persona que se deja pisar.",
  287: "Me pilló desprevenido. / Me agarró en curva.",
  288: "Exmujer. / Exesposa.",
  289: "Aún me falta mucho. / Me queda un largo camino.",
  290: "Largo camino por recorrer. / Falta mucho.",
  291: "Escúchate. / ¿Te oyes lo que dices?",
  292: "Afreinta las consecuencias. / Da la cara.",
  293: "No puedo con la vida. / Me da algo.",
  294: "Depresión otoñal. / Bajón de otoño.",
  295: "Vivir en una nube es la solución. / La ilusión es lo último que se pierde.",
  296: "¡Venga! / ¡Dale!",
  297: "Ni hablar. / Descartado.",
  298: "Sal a la calle. / Pisa el césped (conecta con la realidad).",
  299: "Finge hasta que lo consigas. / Créetelo hasta que sea verdad.",
  300: "Tomando un cafecito. / Disfrutando del café.",
  301: "Me hizo la cruz. / Me ignoró totalmente.",
  302: "Se cree el ladrón que todos son de su condición. / Tú también tienes lo tuyo.",
  303: "No cortes el rollo. / No amargues la fiesta.",
  304: "¿Has bajado de peso? / ¿Estás más delgado?",
  305: "Tiene mucha grasa. / Es muy pringoso.",
  306: "Congeniamos enseguida. / Hicimos buenas migas rápido.",
  307: "Llamé para decir que estaba enfermo. / Me reporté enfermo.",
  308: "Recortar. / Reducir gastos.",
  309: "Escabullirse de. / Salir a hurtadillas.",
  310: "Enparejar a alguien con... / Hacer de celestina.",
  311: "Ya estamos otra vez. / Vuelta la burra al trigo.",
  312: "No quiero obligarte. / No te quiero forzar.",
  313: "Tiene gracia que tú lo digas. / Manda narices que lo digas tú.",
  314: "¡Así me gusta! / ¡Ahora sí nos entendemos!",
  315: "No vendas la piel del oso antes de cazarlo. / No cantes victoria antes de tiempo.",
  316: "¿Qué te parece? / ¿Cómo lo quieres? (comida)",
  317: "Dar una fiesta. / Organizar una fiesta.",
  318: "No le des tantas vueltas. / No busques tres pies al gato.",
  319: "Por preguntar no pierdes nada. / Preguntar en gratis.",
  320: "Me parto de risa. / Me mata de risa.",
  321: "Prefiero no hacerlo. / Paso.",
  322: "Exigente / Tiquismiquis.",
  323: "Me importas. / Te tengo aprecio.",
  324: "No te hagas ilusiones. / No te emociones demasiado.",
  325: "Es un trasto. / Es difícil de llevar (niño/persona).",
  326: "¿Cómo decirlo...? / ¿Cómo te lo explico?",
  327: "Sacrificar a mi perro. / Poner a dormir al perro.",
  328: "Pelota con los de arriba, tirano con los de abajo. / Lamebotas y déspota.",
  329: "Un trasto inútil. / Algo costoso y que no sirve.",
  330: "Crujiente por fuera, tierno por dentro. / El punto perfecto.",
  331: "Salió de la nada. / Apareció de repente.",
  332: "Escarlata. / Rojo pasión.",
  333: "Ponme al día. / Cuéntame qué ha pasado.",
  334: "Me atracaron. / Me asaltaron.",
  335: "No me malinterpretes / Escúchame un momento",
  336: "Icónico. / Emblemático.",
  337: "Con corrientes de aire. / Entra un frío que pela.",
  338: "Masajista. / El/la que da masajes.",
  339: "Es frustrante. / Desesperante.",
  340: "De tranquis. / Discreto.",
  341: "No des la nota. / Pasa desapercibido.",
  342: "Refugio seguro. / Lugar de paz.",
  343: "No seas exagerado. / No te pases.",
  344: "Estoy agotado. / Estoy seco de energía.",
  345: "Te lo mereces. / Tú te lo has buscado.",
  346: "Me apunto / Estoy dentro.",
  347: "Qué pena. / Qué fastidio.",
  348: "Es una bocazas. / Se le va la lengua.",
  349: "Manazas. / Torpe con las manos.",
  350: "Una cosa llevó a la otra. / Y así acabamos.",
  351: "¿Pero qué narices haces? / ¿Qué demonios haces?",
  352: "Tomar el sol. / Chupar sol.",
  353: "Le pillé con las manos en la masa. / Lo agarré in fraganti.",
  354: "No puedo decirle que no a una caña con este calor. / Imposible resistirse a una birra con este sol.",
  355: "¿Y tú qué? / ¿Y a ti?",
  356: "Eso es lo que me hace falta. / Justo lo que necesitaba.",
  357: "Etapas de la vida y transiciones. / Ciclos vitales.",
  358: "Hacer la pelota. / Lamer las botas.",
  359: "Material de marido. / Es para casarse.",
  360: "Me lío. / Confundo las cosas.",
  361: "Dejar a alguien en evidencia. / Poner en ridículo.",
  362: "Ir al grano. / Dejarse de rodeos.",
  363: "Entendido. / Oído cocina.",
  364: "Es pan comido. / Está chupado.",
  365: "Pasar página. / Seguir adelante.",
  366: "Estar en racha. / Estar sembrado.",
  367: "Tocar fondo. / Estar en el hoyo.",
  368: "Empezar de cero. / Borrón y cuenta nueva.",
  369: "Estar en las nubes. / Estar empanao.",
  370: "Hacerse el sueco. / Disimular.",
  371: "Tirar la toalla. / Rendirse.",
  372: "Meter la pata. / Cagarla.",
  373: "Costar un ojo de la cara. / Valer un riñón.",
  374: "Estar sin blanca. / No tener un duro.",
  375: "Ponerse las pilas. / Espabilar.",
  376: "Echar un cable. / Ayudar.",
  377: "Ser uña y carne. / Inseparables.",
  378: "Hablar por los codos. / No callar ni debajo del agua.",
  379: "Estar pez. / No tener ni idea.",
  380: "Tomar el pelo. / Vacilar.",
  381: "Ser un trozo de pan. / Ser muy buena gente.",
  382: "Tener mala leche. / Tener mal carácter.",
  383: "Montar un pollo. / Armar un escándalo.",
  384: "Importar un pimiento. / Me da igual.",
  385: "Estar hasta las narices. / Estar harto.",
  386: "Pedir peras al olmo. / Pedir lo imposible.",
  387: "Buscar una aguja en un pajar. / Algo muy difícil de encontrar.",
  388: "Dar en el clavo. / Acertar de pleno.",
  389: "Estar hecho polvo. / Estar reventado.",
  390: "Dormir como un tronco. / Dormir a pierna suelta.",
  391: "Pasarlo pipa. / Divertirse mucho.",
  392: "Llover a cántaros. / Caer la del pulpo.",
  393: "Estar en el quinto pino. / Estar donde Cristo perdió el mechero.",
  394: "Ser un aguafiestas. / Cortar el rollo.",
  395: "Tener mano izquierda. / Tener tacto.",
  396: "Hacer castillos en el aire. / Soñar despierto.",
  397: "La gota que colmó el vaso. / El colmo.",
  398: "Ver las estrellas. / Darse un golpe fuerte.",
  399: "Estar como una cabra. / Estar loco.",
  400: "No tener pelos en la lengua. / Decir las cosas claras."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
