const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting Batch 7 script...');

const translations = {};
for (let id = 1201; id <= 1400; id++) {
  translations[id] = `Expresión ${id} en español. / Segunda expresión ${id}.`;
}

// Specific translations for Batch 7
Object.assign(translations, {
  1201: "Estar en racha. / Tener buena suerte.",
  1202: "Perder el hilo. / Desorientarse.",
  1203: "Dar en el blanco. / Acertar completamente.",
  1204: "Estar a la última. / Estar actualizado.",
  1205: "Hacer el vacío. / Ignorar a alguien.",
  1206: "Tener presente. / Recordar.",
  1207: "Estar al loro. / Estar atento.",
  1208: "Dar el pego. / Aparentar.",
  1209: "Estar al quite. / Estar preparado.",
  1210: "Hacer la rosca. / Adular.",
  1211: "Tener en cuenta. / Considerar.",
  1212: "Estar a la que salta. / Estar atento a oportunidades.",
  1213: "Dar el cante. / Llamar la atención negativamente.",
  1214: "Estar al pie del cañón. / Estar trabajando.",
  1215: "Hacer la vista gorda. / Ignorar intencionalmente.",
  1216: "Tener palabra. / Cumplir promesas.",
  1217: "Estar a las duras y a las maduras. / En las buenas y en las malas.",
  1218: "Dar el do de pecho. / Esforzarse al máximo.",
  1219: "Estar al tanto. / Estar informado.",
  1220: "Hacer oídos sordos. / Ignorar.",
  1221: "Tener razón. / Estar en lo correcto.",
  1222: "Estar a punto de. / Casi.",
  1223: "Dar el visto bueno. / Aprobar.",
  1224: "Estar al corriente. / Estar informado.",
  1225: "Hacer caso. / Prestar atención.",
  1226: "Tener suerte. / Ser afortunado.",
  1227: "Estar a tope. / Estar muy ocupado.",
  1228: "Dar el sí. / Aceptar.",
  1229: "Estar al día. / Estar actualizado.",
  1230: "Hacer frente. / Enfrentar.",
  1231: "Tener éxito. / Triunfar.",
  1232: "Estar a gusto. / Estar cómodo.",
  1233: "Dar el no. / Rechazar.",
  1234: "Estar al acecho. / Estar vigilante.",
  1235: "Hacer hincapié. / Enfatizar.",
  1236: "Tener ganas. / Desear.",
  1237: "Estar a la altura. / Estar capacitado.",
  1238: "Dar el golpe. / Sorprender.",
  1239: "Estar al límite. / Estar al máximo.",
  1240: "Hacer cola. / Esperar en fila.",
  1241: "Tener hambre. / Estar hambriento.",
  1242: "Estar a la defensiva. / Estar cauteloso.",
  1243: "Dar el salto. / Atreverse.",
  1244: "Estar al margen. / Estar apartado.",
  1245: "Hacer tiempo. / Esperar.",
  1246: "Tener sed. / Estar sediento.",
  1247: "Estar a la expectativa. / Estar esperando.",
  1248: "Dar el paso. / Decidirse.",
  1249: "Estar al mando. / Estar al cargo.",
  1250: "Hacer guardia. / Vigilar.",
  1251: "Tener sueño. / Estar somnoliento.",
  1252: "Estar a la orden del día. / Ser común.",
  1253: "Dar el pistoletazo de salida. / Comenzar.",
  1254: "Estar al servicio. / Estar disponible.",
  1255: "Hacer turno. / Trabajar por turnos.",
  1256: "Tener frío. / Estar frío.",
  1257: "Estar a la venta. / Estar en venta.",
  1258: "Dar el toque. / Avisar.",
  1259: "Estar al volante. / Estar conduciendo.",
  1260: "Hacer noche. / Pernoctar.",
  1261: "Tener calor. / Estar acalorado.",
  1262: "Estar a la vista. / Ser evidente.",
  1263: "Dar el último empujón. / Esfuerzo final.",
  1264: "Estar al frente. / Estar liderando.",
  1265: "Hacer escala. / Hacer parada.",
  1266: "Tener miedo. / Estar asustado.",
  1267: "Estar a la zaga. / Estar rezagado.",
  1268: "Dar el vuelco. / Cambiar drásticamente.",
  1269: "Estar al habla. / Estar en comunicación.",
  1270: "Hacer balance. / Evaluar.",
  1271: "Tener vergüenza. / Estar avergonzado.",
  1272: "Estar a las órdenes. / Estar disponible.",
  1273: "Dar el último toque. / Finalizar.",
  1274: "Estar al alcance. / Estar accesible.",
  1275: "Hacer memoria. / Recordar.",
  1276: "Tener prisa. / Estar apurado.",
  1277: "Estar a medio camino. / Estar a mitad.",
  1278: "Dar el último suspiro. / Morir.",
  1279: "Estar al borde. / Estar al límite.",
  1280: "Hacer méritos. / Esforzarse para conseguir algo.",
  1281: "Tener paciencia. / Ser paciente.",
  1282: "Estar a oscuras. / No saber nada.",
  1283: "Dar el vuelco al marcador. / Cambiar el resultado.",
  1284: "Estar al cabo de la calle. / Estar informado.",
  1285: "Hacer mutis. / Irse en silencio.",
  1286: "Tener cuidado. / Ser cuidadoso.",
  1287: "Estar a punto de caramelo. / En el momento perfecto.",
  1288: "Dar el último adiós. / Despedirse finalmente.",
  1289: "Estar al dedillo. / Saber perfectamente.",
  1290: "Hacer novillos. / Faltar a clase.",
  1291: "Tener celos. / Estar celoso.",
  1292: "Estar a régimen. / Estar a dieta.",
  1293: "Dar el último retoque. / Ajuste final.",
  1294: "Estar al descubierto. / Estar expuesto.",
  1295: "Hacer pellas. / Faltar a clase.",
  1296: "Tener envidia. / Estar envidioso.",
  1297: "Estar a salvo. / Estar seguro.",
  1298: "Dar el último vistazo. / Revisar por última vez.",
  1299: "Estar al detalle. / Con precisión.",
  1300: "Hacer pinitos. / Dar los primeros pasos.",
  1301: "Tener razón. / Estar correcto.",
  1302: "Estar a solas. / Estar solo.",
  1303: "Dar el último zarpazo. / Ataque final.",
  1304: "Estar al dictado. / Seguir órdenes.",
  1305: "Hacer rabona. / Faltar.",
  1306: "Tener fe. / Creer.",
  1307: "Estar a sus anchas. / Estar cómodo.",
  1308: "Dar el vuelco definitivo. / Cambio total.",
  1309: "Estar al filo. / En el límite.",
  1310: "Hacer rancho aparte. / Separarse del grupo.",
  1311: "Tener esperanza. / Ser esperanzado.",
  1312: "Estar a tiempo. / Llegar a tiempo.",
  1313: "Dar el último coletazo. / Último esfuerzo.",
  1314: "Estar al grano. / Ir al punto.",
  1315: "Hacer sombra. / Opacar.",
  1316: "Tener confianza. / Confiar.",
  1317: "Estar a toda máquina. / A máxima velocidad.",
  1318: "Dar el último empuje. / Impulso final.",
  1319: "Estar al loro de. / Estar atento a.",
  1320: "Hacer su agosto. / Aprovechar.",
  1321: "Tener dudas. / Dudar.",
  1322: "Estar a todo trapo. / A toda velocidad.",
  1323: "Dar el último tirón. / Esfuerzo final.",
  1324: "Estar al pairo. / Estar inactivo.",
  1325: "Hacer tabla rasa. / Empezar de cero.",
  1326: "Tener certeza. / Estar seguro.",
  1327: "Estar a trancas y barrancas. / Con dificultad.",
  1328: "Dar el último respiro. / Último aliento.",
  1329: "Estar al quite de. / Estar preparado para.",
  1330: "Hacer trizas. / Destrozar.",
  1331: "Tener claridad. / Ver claro.",
  1332: "Estar a vueltas con. / Estar lidiando con.",
  1333: "Dar el vuelco final. / Cambio definitivo.",
  1334: "Estar al rojo vivo. / Estar muy tenso.",
  1335: "Hacer un aparte. / Hablar en privado.",
  1336: "Tener convicción. / Estar convencido.",
  1337: "Estar al acecho de. / Estar vigilando.",
  1338: "Dar el último jalón. / Tirón final.",
  1339: "Estar al socaire. / Estar protegido.",
  1340: "Hacer un paréntesis. / Hacer una pausa.",
  1341: "Tener determinación. / Estar determinado.",
  1342: "Estar al albur. / Al azar.",
  1343: "Dar el último manotazo. / Golpe final.",
  1344: "Estar al tanto de. / Estar informado de.",
  1345: "Hacer un apunte. / Anotar.",
  1346: "Tener firmeza. / Ser firme.",
  1347: "Estar al alza. / Estar subiendo.",
  1348: "Dar el último mordisco. / Último intento.",
  1349: "Estar al timón. / Estar al mando.",
  1350: "Hacer un balance. / Evaluar.",
  1351: "Tener voluntad. / Tener ganas.",
  1352: "Estar al baja. / Estar bajando.",
  1353: "Dar el último bocado. / Último pedazo.",
  1354: "Estar al trasluz. / A contraluz.",
  1355: "Hacer un cálculo. / Calcular.",
  1356: "Tener temple. / Ser valiente.",
  1357: "Estar al corriente de. / Saber de.",
  1358: "Dar el último empellón. / Empujón final.",
  1359: "Estar al uso. / Estar de moda.",
  1360: "Hacer un descuento. / Descontar.",
  1361: "Tener coraje. / Ser valiente.",
  1362: "Estar al día de. / Estar actualizado sobre.",
  1363: "Dar el último estiron. / Crecimiento final.",
  1364: "Estar al vapor. / Al vapor.",
  1365: "Hacer un esfuerzo. / Esforzarse.",
  1366: "Tener agallas. / Tener valor.",
  1367: "Estar al fondo. / En el fondo.",
  1368: "Dar el último grito. / Último aviso.",
  1369: "Estar al viento. / Al aire libre.",
  1370: "Hacer un favor. / Ayudar.",
  1371: "Tener arrestos. / Tener valentía.",
  1372: "Estar al fresco. / Al aire libre.",
  1373: "Dar el último hurra. / Último esfuerzo.",
  1374: "Estar al sol. / Bajo el sol.",
  1375: "Hacer un gesto. / Gesticular.",
  1376: "Tener bríos. / Tener energía.",
  1377: "Estar al fuego. / Al fuego.",
  1378: "Dar el último intento. / Intento final.",
  1379: "Estar al aire. / Al aire.",
  1380: "Hacer un guiño. / Guiñar.",
  1381: "Tener empuje. / Tener impulso.",
  1382: "Estar al horno. / Al horno.",
  1383: "Dar el último latigazo. / Golpe final.",
  1384: "Estar al baño. / En el baño.",
  1385: "Hacer un hueco. / Hacer espacio.",
  1386: "Tener ímpetu. / Tener fuerza.",
  1387: "Estar al natural. / Al natural.",
  1388: "Dar el último manotón. / Manotazo final.",
  1389: "Estar al dente. / Al dente.",
  1390: "Hacer un inciso. / Hacer una aclaración.",
  1391: "Tener pujanza. / Tener vigor.",
  1392: "Estar al punto. / En su punto.",
  1393: "Dar el último navajazo. / Ataque final.",
  1394: "Estar al rojo. / Al rojo.",
  1395: "Hacer un inventario. / Inventariar.",
  1396: "Tener vigor. / Ser vigoroso.",
  1397: "Estar al sereno. / Al aire libre de noche.",
  1398: "Dar el último pinchazo. / Golpe final.",
  1399: "Estar al vacío. / En el vacío.",
  1400: "Hacer un llamamiento. / Llamar la atención."
});

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
