const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting script...');

const translations = {
  1: "Me sacaba tres años. / Iba tres cursos por delante de mí.",
  2: "Iba tres años por detrás de mí. / Le sacaba tres años.",
  3: "Ni por asomo. / Estás muy equivocado.",
  4: "Guárdame el sitio. / No dejes que me quiten la silla.",
  5: "Huevos de gallinas camperas. / Huevos ecológicos.",
  6: "Me da en la nariz. / Tengo una corazonada.",
  7: "Es un metomentodo. / Es muy cotilla.",
  8: "No me tires de la lengua sobre su novio. / Mejor ni hablemos de su novio.",
  9: "No hay más remedio. / Es lo que hay.",
  10: "Por pura necesidad. / Porque no quedaba otra.",
  11: "No tenía otra opción. / No me quedó más remedio.",
  12: "Ya que sacas el tema. / Ahora que lo dices.",
  13: "Lo hago por inercia. / Actúo en piloto automático.",
  14: "No soy de los que se arrepienten fácilmente. / No suelo darle vueltas a las cosas.",
  15: "Sushi giratorio. / Restaurante de cinta.",
  16: "Cilantro. / Perejil chino.",
  17: "De la nada. / Sin venir a cuento.",
  18: "Te dejo en paz. / Dejaré de molestarte.",
  19: "Un fuerte aplauso para... / Démosle un gran aplauso a...",
  20: "Tengo algo que comentar. / Hay algo que quiero hablar contigo.",
  21: "¿Quién eres tú para decir eso? / ¿Tú qué sabrás?",
  22: "Aclaremos los malentendidos antes de irnos. / Dejemos las cosas claras antes de salir.",
  23: "Solo digo. / Es solo un comentario.",
  24: "Soy muy temperamental. / Tengo muchos altibajos.",
  25: "Está fallando. / Se está portando mal (máquina/cuerpo).",
  26: "Es un engorro. / Qué inoportuno.",
  27: "Vive la vida al máximo. / Disfruta cada momento.",
  28: "Me ha dado el mal del puerco. / Estoy empachado.",
  29: "Me parece un buen plan. / Suena bien.",
  30: "No es una reacción impulsiva. / No lo digo en caliente.",
  31: "No es cumplir por cumplir. / Va en serio.",
  32: "Hablo en serio. / No estoy bromeando.",
  33: "¿Te apuntas a cenar? / ¿Te hace una cena?",
  34: "Ojalá pudiera. / Me encantaría, pero no puedo.",
  35: "Parejas. / Medias naranjas.",
  36: "Claro que sí. / Dalo por hecho.",
  37: "Yo me encargo. / Cuenta conmigo.",
  38: "Aquí tienes. / Toma.",
  39: "Aplaudir. / Ovacionar.",
  40: "Léeme los labios. / Escucha bien lo que te digo.",
  41: "Tengo un espíritu joven. / Soy joven de corazón.",
  42: "Irse a pique. / Salir mal.",
  43: "¿Te comió la lengua el gato? / ¿Por qué tan callado?",
  44: "No me quito la sensación de encima. / Tengo un presentimiento que no se va.",
  45: "Te lo recomiendo mucho. / Es súper recomendable.",
  46: "Pon el móvil en silencio. / Silencia el celular.",
  47: "La responsabilidad es mía. / Aquí se decide todo.",
  48: "Tengo la agenda llena. / No tengo huecos.",
  49: "Hoy tengo el día a tope. / Estoy a full hoy.",
  50: "Estaba totalmente ocupado. / Tenía todo completo.",
  51: "Amigo del barrio. / Colega de la zona.",
  52: "Me siento joven. / El espíritu no envejece.",
  53: "Dispara. / Pregunta lo que quieras.",
  54: "Hasta el mejor escribano echa un borrón. / Cualquiera puede equivocarse.",
  55: "Patear la calle. / Gastar suela.",
  56: "¿Y ahora qué? / ¿Qué hacemos ahora?",
  57: "¿Que de dónde soy? ¡Esta es nuestra tierra! / Soy de aquí de toda la vida.",
  58: "Esto es una locura. / Es de locos.",
  59: "Indignante. / Es una barbaridad.",
  60: "Eso te lo concedo. / En eso tienes razón.",
  61: "Se me fue el santo al cielo con el trabajo. / Me enfrasqué demasiado en el trabajo.",
  62: "Me vendría bien un café. / Necesito café urgentemente.",
  63: "Tengo el cerebro frito. / No me da la cabeza para más.",
  64: "¿Para qué molestarse? / ¿Qué sentido tiene?",
  65: "Desconectar. / Relajarse.",
  66: "¿Sabes qué? / Adivina qué.",
  67: "De antemano. / Con antelación.",
  68: "Parecer demasiado intenso. / Ser muy brusco.",
  69: "Me quedé alucinado. / Me dejó sin palabras.",
  70: "He estado insoportable últimamente. / He dado mucha guerra.",
  71: "Pasar por. / Revisar.",
  72: "No hace falta ni decirlo. / Se cae de maduro.",
  73: "Me gusta el hecho de que... / Me mola que...",
  74: "Pase lo que pase. / Cueste lo que cueste.",
  75: "Dada mi experiencia. / Según lo que he vivido.",
  76: "Tragarme mis palabras. / Rectificar.",
  77: "Estar a la altura de mis expectativas. / Cumplir con lo que esperaba.",
  78: "Adictivo. / De los que no puedes parar de comer.",
  79: "Nunca tuve oportunidad. / No tenía nada que hacer.",
  80: "Supongo que debí verlo venir. / Me lo tenía que haber imaginado.",
  81: "¿Cómo te sientes hoy? / ¿Qué tal estás hoy?",
  82: "Sacar de quicio. / Fastidiar.",
  83: "Veterinario / Veterano (según contexto).",
  84: "¿Dónde está la trampa? / ¿Qué hay detrás de esto?",
  85: "No hace falta que traigas nada. / No te molestes en traer nada.",
  86: "Me estoy tratando el hombro. / Estoy yendo a rehabilitación por el hombro.",
  87: "Coronilla. / La parte alta de la cabeza.",
  88: "Estoy muy indeciso. / Estoy hecho un lío.",
  89: "En el limbo. / En el aire.",
  90: "Es legal. / Es de fiar.",
  91: "Es un partidazo. / Vale la pena.",
  92: "No te lo tomes a mal. / No te enfades por eso.",
  93: "No me arrepiento de mucho. / No tengo muchos remordimientos.",
  94: "Crisis de los cuarenta. / Crisis de la mediana edad.",
  95: "No seas tan dramático. / No montes un drama.",
  96: "No me vengas con lloriqueos. / Deja de quejarte.",
  97: "No tengo palabras. / -Me has dejado mudo.",
  98: "¿Pillaste eso? / ¿Te diste cuenta?",
  99: "Señales sociales. / Indirectas sociales.",
  100: "¿Te percataste de eso? / ¿Lo notaste?",
  101: "¿Te enteraste de la oferta de trabajo de Mark? / ¿Supiste lo de Mark?",
  102: "Paquete de beneficios. / Prestaciones.",
  103: "Es difícil de decir. / Complicado saberlo.",
  104: "Si estuvieras en mi lugar. / Si estuvieras en mis zapatos.",
  105: "Esto es lo primero. / Esto tiene prioridad.",
  106: "¿Te suena? / ¿Te resulta familiar?",
  107: "Ya era hora. / Se ha hecho esperar.",
  108: "Apogeo. / Mejor momento.",
  109: "No hacen falta disculpas. / No tienes que disculparte.",
  110: "Madura. / Crece un poco.",
  111: "Suele contestar rápido. / Está siempre pendiente para responder.",
  112: "El beneficio de la duda. / Confianza ciega momentánea.",
  113: "Despejar la mente. / Pensar en otra cosa.",
  114: "Ponte en mi lugar. / Sé empático.",
  115: "Pasar desapercibido. / Mantener un perfil bajo.",
  116: "Deberías centrarte en lo tuyo. / Enfócate en lo que te toca.",
  117: "Ya he pasado por eso. / Me sé la historia.",
  118: "Por las risas. / Para pasar el rato.",
  119: "El coso ese. / El chisme ese.",
  120: "Explícamelo paso a paso. / Guíame.",
  121: "Facturación / Rotación de personal / Darse la vuelta.",
  122: "Sigue así. / No lo dejes.",
  123: "Me he arreglado el pelo. / Fui a la peluquería.",
  124: "Hace un siglo. / Cuánto tiempo.",
  125: "Han pasado años. / Hace una eternidad.",
  126: "Defraudar a alguien. / Decepcionar.",
  127: "Te has saltado mucho. / Te has pasado tres pueblos.",
  128: "Pon esto en 'ahora'. / Actualiza la posición.",
  129: "Solucionar. / Ordenar.",
  130: "Desconectar un poco. / Quitarme cosas de la cabeza.",
  131: "No entendí nada. / Me habló en chino.",
  132: "Me supera. / No me entero de nada.",
  133: "Empatamops. / Estamos a la par.",
  134: "Estamos en paz. / Cuentas saldadas.",
  135: "Suéltalo. / Cuéntamelo todo.",
  136: "Cóbrame. / La cuenta, por favor.",
  137: "Fuera de nuestro alcance. / Es otra liga.",
  138: "Tengo una crisis nerviosa. / Me va a dar algo.",
  139: "Procrastinar. / Dejar para mañana.",
  140: "Lo he tenido en mente. / Le he estado dando vueltas.",
  141: "Sopesar los pros y los contras. / Valorar lo bueno y lo malo.",
  142: "Volver a encarrilar las cosas. / Poner todo en orden de nuevo.",
  143: "¿Qué te corroe? / ¿Qué te pasa?",
  144: "Dadle un fuerte aplauso. / Un aplauso para ella.",
  145: "¿Cómo te va? / ¿Qué tal todo?",
  146: "Me apunto. / Cuenta conmigo.",
  147: "No podré ir. / Me es imposible.",
  148: "No hay mal que por bien no venga. / Una bendición disfrazada.",
  149: "Lo dejamos para otro día. / Te lo debo para la próxima.",
  150: "Depende de ti. / Tú decides.",
  151: "¿A qué hora embarcamos? / ¿Cuándo es el embarque?",
  152: "¿El vuelo sale a su hora? / ¿Va puntual?",
  153: "¿Me puede dar ventanilla? / Quiero sitio en la ventana.",
  154: "¿Cuánto dura el vuelo? / ¿Cuánto tiempo de viaje es?",
  155: "¿Dónde está el baño más cercano? / ¿El servicio?",
  156: "Estoy esperando para embarcar. / En la cola de embarque.",
  157: "¿Qué hiciste el finde? / ¿Qué tal el fin de semana?",
  158: "Cárgalo a mi habitación. / A mi cuenta de la habitación.",
  159: "Indeciso. / Dudando.",
  160: "Pónmelo en la tarjeta. / Cobramelo con tarjeta.",
  161: "¿Hay wifi gratis? / ¿Tenéis wifi?",
  162: "Solo estoy mirando. / Solo echo un ojo.",
  163: "¿Esto tiene descuento? / ¿Está rebajado?",
  164: "¿Me lo puedo probar? / ¿Dónde están los probadores?",
  165: "¿Tenéis una talla más grande? / ¿Hay talla L?",
  166: "Quiero devolver esto. / Vengo a hacer una devolución.",
  167: "¿Dónde se paga? / ¿La caja?",
  168: "¿Aceptáis tarjeta? / ¿Se puede pagar con tarjeta?",
  169: "Quédate el cambio. / Así está bien.",
  170: "¿Me das una bolsa? / ¿Tienes bolsa?",
  171: "Me he perdido. / No sé dónde estoy.",
  172: "¿Qué lugar es este? / ¿Dónde estamos?",
  173: "¿Nos puedes hacer una foto? / ¿Te importa sacarnos una foto?",
  174: "Me he quedado sin batería. / Se me murió el móvil.",
  175: "¿Tienes un cargador portátil? / ¿Una batería externa?",
  176: "¿Está ocupado? / ¿Hay alguien aquí?",
  177: "No me encuentro bien. / Me siento mal.",
  178: "Para bien o para mal. / Sea como sea.",
  179: "¿Ya hemos llegado? / ¿Falta mucho?",
  180: "¿A cuánto estamos? / ¿Cuánto queda?",
  181: "Hay atasco. / Tráfico pesado.",
  182: "No te cueles. / A la cola.",
  183: "Permiso. / Déjame pasar.",
  184: "Cuidado. / Es una trampa.",
  185: "Ojo. / Fíjate bien.",
  186: "Come despacio. / No corras.",
  187: "Quiero esto. / Me pido este.",
  188: "Sin cilantro. / Quítale el cilantro.",
  189: "Pica mucho. / Está muy picante.",
  190: "Agua. / Un agua, porfa.",
  191: "La cuenta. / Cobrar.",
  192: "Pagamos a medias. / Cada uno lo suyo.",
  193: "Invito yo. / Pago yo.",
  194: "La próxima pagas tú. / A la siguiente invitas tú.",
  195: "Está muy rico. / Buenísimo.",
  196: "Estoy lleno. / No puedo más.",
  197: "Para llevar. / Pónmelo para llevar.",
  198: "¡Salud! / ¡Chinchín!",
  199: "Otra ronda. / Ponme otra.",
  200: "Borracho. / Pasado de copas."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
