const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting script...');

const translations = {
  801: "Frustrar a mi hermana. / Sacar de quicio a mi hermana.",
  802: "Algo no cuadra / Me siento pachucho.",
  803: "No soy yo mismo. / Estoy raro.",
  804: "Tu mejor opción. / Lo que más te conviene.",
  805: "Ando justo de tiempo / Se me acaba el tiempo / Contra reloj.",
  806: "No puedo con esto. / Me supera.",
  807: "Sonará cursi / Puede sonar obvio.",
  808: "No está nada mal. / Bastante decente.",
  809: "Un spa para mim arme. / Relajarme en el spa.",
  810: "Se me escapó. / Me salió sin querer.",
  811: "Agridulce. / Sentimientos encontrados.",
  812: "No te lo tengas tan creído / No te creas tanto.",
  813: "Deja de molestarme / Ya basta / Para de incordiar.",
  814: "Haz lo que quieras / Allá tú.",
  815: "Consultártelo / Hablarlo contigo.",
  816: "He estado ocupado. / Andaba liado.",
  817: "No te vas a morir. / Sobrevivirás.",
  818: "Tomarte bajo mi ala. / Cuidar de ti.",
  819: "Para nada. / En vano.",
  820: "Te debo una. / Estoy en deuda.",
  821: "Hay algo entre ellos. / Tienen rollo.",
  822: "Aclarar las cosas. / Limpiar el ambiente.",
  823: "Estorbar. / Ser un obstáculo.",
  824: "Tensos. / Al borde del colapso.",
  825: "¡Tío! / ¡Vaya!",
  826: "Se respira primavera. / Huele a primavera.",
  827: "Está loco. / Es una locura.",
  828: "Inocentada. / Broma del Día de los Inocentes.",
  829: "A espaldas de alguien. / A sus espaldas.",
  830: "Dale recuerdos de mi parte. / Salúdale.",
  831: "Sin ánimo de ofender. / No te lo tomes a mal.",
  832: "¿Me sigues? / ¿Me entiendes?",
  833: "Relájate / Tranqui.",
  834: "Matrícula. / Colegiatura.",
  835: "Cada dos días. / Un día sí, otro no.",
  836: "Chivarse. / Delatar.",
  837: "Pasarse. / Excederse.",
  838: "Tener un problema con. / Tener roces.",
  839: "Ir tirando. / Apañárselas.",
  840: "Emocionado. / Conmovido.",
  841: "Mantecoso. / Suave como la mantequilla.",
  842: "Cabecear. / Dar una cabezada.",
  843: "Por los pelos. / Casi no lo cuentas.",
  844: "En otro color. / De otra tonalidad.",
  845: "Cacharro. / Trasto (coche defectuoso).",
  846: "Táper para llevar. / Envase para sobras.",
  847: "No lo tolero. / No lo acepto.",
  848: "Interrumpir / Cortar el paso.",
  849: "Así es la vida. / Qué le vamos a hacer.",
  850: "Suéltalo ya. / Desembucha.",
  851: "Falleció y fue incinerado. / Murió y lo cremaron.",
  852: "Depresión otoñal. / Melancolía de otoño.",
  853: "Espera ahí. / No te muevas.",
  854: "En paro. / Entre trabajos.",
  855: "Restregárselo. / Echárselo en cara.",
  856: "Soso. / Insípido.",
  857: "Tragárselo todo. / Creérselo a pies juntillas.",
  858: "A la vuelta de la esquina. / Muy cerca.",
  859: "Algo. / Un tanto.",
  860: "Dar por sentado. / No valorar.",
  861: "Para siempre. / Definitivamente.",
  862: "Tomárselo como algo personal. / Sentirse aludido.",
  863: "Dejarlo para el último momento. / Apurar hasta el final.",
  864: "Pegajoso. / Dependiente.",
  865: "Me importa un bledo. / Me da absolutamente igual.",
  866: "No lo gafes. / No lo maldigas.",
  867: "Cállate ya. / Deja de parlotear.",
  868: "Cumplir todos los requisitos. / Tener todo lo necesario.",
  869: "Anotarlo antes de olvidarlo. / Apuntarlo por si acaso.",
  870: "Despreocupado. / Indiferente.",
  871: "Ha sido increíble. / Fue alucinante.",
  872: "Trasnochar. / Pasar la noche en vela.",
  873: "Hacer que el corazón lata más fuerte. / Enamorar.",
  874: "¿Estoy alucinando? / ¿Me lo estoy imaginando?",
  875: "No puedo de ninguna manera. / Es imposible para mí.",
  876: "¿Inviertes en bolsa? / ¿Juegas en la bolsa?",
  877: "Mercado de valores. / Bolsa (estilo periodístico).",
  878: "Lograrlo. / Conseguirlo.",
  879: "En serio. / Sin mentir.",
  880: "Encajar perfectamente. / Cumplir con lo necesario.",
  881: "Estoy trabajando. / Estoy en horario laboral.",
  882: "Hay algo de niebla. / Está un poco nublado (mental).",
  883: "Tengo el sueño ligero. / Me despierto fácil.",
  884: "Suelo ser tímido. / Tiendo a ser reservado.",
  885: "Tímido ante la cámara. / No le gustan las fotos.",
  886: "Está como nuevo. / Parece nuevo.",
  887: "Tienen mucho en común. / Se parecen bastante.",
  888: "Muy típico de ti. / Eso es muy tuyo.",
  889: "Cuídate. / Recupérate bien.",
  890: "¡Adelante! / ¡A por ello!",
  891: "Es un caso. / Es complicado.",
  892: "No te defraudaré. / No te fallaré.",
  893: "He intentado contactarte. / Te he estado buscando.",
  894: "Fue un golpe de suerte. / Pura chiripa.",
  895: "No reprimas tus sentimientos. / Exprésate.",
  896: "No seas tímido. / Anímate.",
  897: "Me estás cayendo bien. / Cada vez me gustas más.",
  898: "Quemé las pestañas. / Trabajé hasta tarde.",
  899: "Falta poco para dos minutos. / Casi dos minutos.",
  900: "Ese sería el mejor escenario. / Eso sería lo ideal.",
  901: "Totalmente de acuerdo. / No podría estar más de acuerdo.",
  902: "Tengo memoria de pez. / Se me olvida todo.",
  903: "Invita la casa. / Es cortesía.",
  904: "Deberías pedir una segunda opinión. / Consulta con otro.",
  905: "Eres el mejor. / No hay nadie como tú.",
  906: "No me tomes el pelo. / No me vaciles.",
  907: "Estoy dividido. / No sé qué hacer.",
  908: "Has perdido el hilo. / No entiendes nada.",
  909: "Que quede entre nosotros. / Es nuestro secreto.",
  910: "Ya sabes cómo va. / Conoces el procedimiento.",
  911: "Ha sido una montaña rusa. / Muchos altibajos.",
  912: "Te admiro. / Eres mi referente.",
  913: "Está sobrevalorado. / No es para tanto.",
  914: "Resumiendo. / En pocas palabras.",
  915: "No guardo rencor. / No soy rencoroso.",
  916: "Ahora mismo no lo sé. / No me acuerdo de memoria.",
  917: "Estoy harto. / Ya no aguanto más.",
  918: "Tengo mucho trabajo. / Estoy saturado.",
  919: "Soy un desastre con las direcciones. / Me pierdo fácil.",
  920: "¿Cómo lo llevas? / ¿Cómo aguantas?",
  921: "Solo tienes que hacerlo. / Simplemente hazlo.",
  922: "¿Qué tienes pensado? / ¿Qué planeas?",
  923: "No seas así. / No te pongas así.",
  924: "Pongamos esto en marcha. / Empecemos.",
  925: "Cuesta un ojo de la cara. / Es carísimo.",
  926: "No lo hagas sin ganas. / No finjas.",
  927: "Me quitaste las palabras de la boca. / Iba a decir lo mismo.",
  928: "Te pasaste de la raya. / Cruzaste el límite.",
  929: "Sabe de lo suyo. / Es un experto.",
  930: "¡Aguanta! / ¡Resiste!",
  931: "Tienes que romper con ese hábito. / Deja esa costumbre.",
  932: "Diste en el clavo. / Acertaste de lleno.",
  933: "Mi cerebro ya no es lo que era. / He perdido facultades.",
  934: "Me timaron. / Me estafaron.",
  935: "Estoy fuera dando vueltas. / Ando por ahí.",
  936: "No me lo puedo quitar de la cabeza. / Me obsesiona.",
  937: "No te engañes. / Sé realista.",
  938: "No es un paseo. / No es fácil.",
  939: "Déjalo estar. / Olvídalo.",
  940: "Recapacita. / Entra en razón.",
  941: "Dejémoslo por hoy. / Terminemos.",
  942: "Compórtate según tu edad. / Madura.",
  943: "No lo entendí. / Se me escapó.",
  944: "¿Abren hoy? / ¿Están abiertos?",
  945: "No exageres. / No hagas un drama.",
  946: "En resumen. / Resumiendo.",
  947: "No cuentes el secreto. / Guarda el secreto.",
  948: "¿Están abiertos? / ¿Hay servicio?",
  949: "Estaré atento. / Vigilaré.",
  950: "Te apoyo. / Cuento contigo.",
  951: "Otra vez lo mismo. / Ya empezamos.",
  952: "Ya me lo imaginaba. / Lo sabía.",
  953: "Obvio. / Lógico.",
  954: "Déjame en paz. / No me molestes.",
  955: "Ya pasé por eso. / Conozco la situación.",
  956: "Trabajamos con lo mínimo. / Personal reducido.",
  957: "Ahí está el problema. / Ese es el tema.",
  958: "Intrigante. / Fascinante.",
  959: "Pasa constantemente. / Es habitual.",
  960: "No hay prueba concluyente. / Falta evidencia clara.",
  961: "Es pan comido. / Facilísimo.",
  962: "Me pone de los nervios. / Me saca de quicio.",
  963: "Estoy en ello. / Trabajando en eso.",
  964: "No me presiones. / Dame tiempo.",
  965: "Estoy en blanco. / No se me ocurre nada.",
  966: "Déjame pensarlo. / Lo medito.",
  967: "Está en juego. / Hay mucho en riesgo.",
  968: "Punto muerto. / Estancados.",
  969: "Retractarse. / Dar marcha atrás.",
  970: "Hacer las paces. / Reconciliarse.",
  971: "Dar el primer paso. / Tomar la iniciativa.",
  972: "Llegar a un acuerdo. / Negociar.",
  973: "Romper el silencio. / Hablar primero.",
  974: "Dejar atrás. / Superar.",
  975: "Seguir adelante. / Continuar.",
  976: "Pasar página. / Empezar de nuevo.",
  977: "Cerrar el capítulo. / Terminar con eso.",
  978: "Nuevo capítulo. / Comenzar algo nuevo.",
  979: "Tomar un descanso. / Hacer una pausa.",
  980: "Recargar pilas. / Recuperar energía.",
  981: "Desconectar. / Relajarse.",
  982: "Con calma. / Sin prisa.",
  983: "Paso a paso. / Poco a poco.",
  984: "Roma no se hizo en un día. / Todo lleva tiempo.",
  985: "La práctica hace al maestro. / Practicando se aprende.",
  986: "Nunca es tarde. / Siempre se puede aprender.",
  987: "Cada día se aprende. / Aprendizaje continuo.",
  988: "Saber es poder. / El conocimiento es clave.",
  989: "La experiencia enseña. / Se aprende de los errores.",
  990: "Vivir y aprender. / Aprender de la vida.",
  991: "Errar es humano. / Todos nos equivocamos.",
  992: "Nadie es perfecto. / Todos tenemos defectos.",
  993: "Los errores son normales. / Equivocarse es natural.",
  994: "Aprender de los errores. / Crecer con las equivocaciones.",
  995: "No hay mal que por bien no venga. / Todo tiene su lado positivo.",
  996: "Tras la tormenta, calma. / Todo pasa.",
  997: "Al mal tiempo, buena cara. / Mantener el ánimo.",
  998: "No llorar sobre leche derramada. / Lo hecho, hecho está.",
  999: "Más vale prevenir. / Mejor prevenir.",
  1000: "Más vale tarde. / Mejor tarde que nunca."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
