const fs = require('fs');
const path = 'c:\\Users\\heroy\\COL_ENG\\db\\20260101_COL_ENG_1484_backupjson';

console.log('Starting Batch 6 script...');

const translations = {
  1001: "Ni lo sueñes. / Imposible.",
  1002: "Estoy en ello. / Trabajando en eso.",
  1003: "No me presiones. / Dame espacio.",
  1004: "Estoy en blanco. / No se me ocurre nada.",
  1005: "Déjame pensarlo. / Lo medito.",
  1006: "Está en juego. / Hay mucho en riesgo.",
  1007: "Punto muerto. / Estancados.",
  1008: "Retractarse. / Dar marcha atrás.",
  1009: "Hacer las paces. / Reconciliarse.",
  1010: "Dar el primer paso. / Tomar la iniciativa.",
  1011: "Llegar a un acuerdo. / Ponerse de acuerdo.",
  1012: "Romper el silencio. / Hablar primero.",
  1013: "Dejar atrás. / Superar.",
  1014: "Seguir adelante. / Continuar.",
  1015: "Pasar página. / Empezar de nuevo.",
  1016: "Cerrar el capítulo. / Terminar con eso.",
  1017: "Nuevo capítulo. / Comenzar algo nuevo.",
  1018: "Tomar un descanso. / Hacer una pausa.",
  1019: "Recargar pilas. / Recuperar energía.",
  1020: "Desconectar. / Relajarse.",
  1021: "Con calma. / Sin prisa.",
  1022: "Paso a paso. / Poco a poco.",
  1023: "Roma no se hizo en un día. / Todo lleva tiempo.",
  1024: "La práctica hace al maestro. / Practicando se aprende.",
  1025: "Nunca es tarde. / Siempre se puede aprender.",
  1026: "Cada día se aprende. / Aprendizaje continuo.",
  1027: "Saber es poder. / El conocimiento es clave.",
  1028: "La experiencia enseña. / Se aprende de los errores.",
  1029: "Vivir y aprender. / Aprender de la vida.",
  1030: "Errar es humano. / Todos nos equivocamos.",
  1031: "Nadie es perfecto. / Todos tenemos defectos.",
  1032: "Los errores son normales. / Equivocarse es natural.",
  1033: "Aprender de los errores. / Crecer con las equivocaciones.",
  1034: "No hay mal que por bien no venga. / Todo tiene su lado positivo.",
  1035: "Tras la tormenta, calma. / Todo pasa.",
  1036: "Al mal tiempo, buena cara. / Mantener el ánimo.",
  1037: "No llorar sobre leche derramada. / Lo hecho, hecho está.",
  1038: "Más vale prevenir. / Mejor prevenir.",
  1039: "Más vale tarde. / Mejor tarde que nunca.",
  1040: "Nunca digas nunca. / Todo es posible.",
  1041: "Donde hay voluntad, hay camino. / Querer es poder.",
  1042: "El que la sigue, la consigue. / La perseverancia paga.",
  1043: "No dejes para mañana. / Hazlo hoy.",
  1044: "Más vale pájaro en mano. / Asegura lo que tienes.",
  1045: "Camarón que se duerme. / El que no se mueve, pierde.",
  1046: "A caballo regalado. / No seas exigente con regalos.",
  1047: "Dime con quién andas. / Las compañías definen.",
  1048: "Más sabe el diablo por viejo. / La experiencia cuenta.",
  1049: "En boca cerrada no entran moscas. / Mejor callar.",
  1050: "A palabras necias, oídos sordos. / Ignora las tonterías.",
  1051: "Haz el bien sin mirar a quién. / Ayuda sin esperar nada.",
  1052: "Agua que no has de beber. / No te metas donde no te llaman.",
  1053: "Cría cuervos. / La ingratitud duele.",
  1054: "Perro que ladra no muerde. / Las amenazas vacías.",
  1055: "Más vale solo que mal acompañado. / Mejor la soledad.",
  1056: "El que mucho abarca poco aprieta. / No te disperses.",
  1057: "A mal tiempo, buena cara. / Optimismo ante adversidad.",
  1058: "No es oro todo lo que reluce. / Las apariencias engañan.",
  1059: "Ojos que no ven. / La ignorancia es felicidad.",
  1060: "Del dicho al hecho. / Entre palabras y acciones hay distancia.",
  1061: "Quien siembra vientos. / Las consecuencias de tus actos.",
  1062: "A buen entendedor. / Con pocas palabras basta.",
  1063: "Más vale maña que fuerza. / La inteligencia supera la fuerza.",
  1064: "No hay peor sordo. / El que no quiere escuchar.",
  1065: "Hombre prevenido. / La preparación es clave.",
  1066: "El hábito no hace al monje. / La ropa no define.",
  1067: "Cuando el río suena. / Algo de verdad hay.",
  1068: "A quien madruga. / Los que se esfuerzan ganan.",
  1069: "Más vale tarde que nunca. / Mejor llegar tarde.",
  1070: "En casa del herrero. / Las ironías de la vida.",
  1071: "Genio y figura. / La gente no cambia.",
  1072: "Cada loco con su tema. / Cada quien con sus manías.",
  1073: "A falta de pan. / Conformarse con lo que hay.",
  1074: "Zapatero a tus zapatos. / Ocúpate de lo tuyo.",
  1075: "Donde fueres, haz lo que vieres. / Adáptate al entorno.",
  1076: "Muerto el perro. / Elimina la causa del problema.",
  1077: "Gato escaldado. / El que aprende de malas experiencias.",
  1078: "A rey muerto, rey puesto. / La vida continúa.",
  1079: "Aunque la mona se vista de seda. / La esencia no cambia.",
  1080: "Dios los cría. / Los iguales se juntan.",
  1081: "El que tiene boca se equivoca. / Todos cometemos errores al hablar.",
  1082: "Hacer de tripas corazón. / Armarse de valor.",
  1083: "Tirar la casa por la ventana. / Gastar sin medida.",
  1084: "Estar en las nubes. / Distraído.",
  1085: "Tomar el pelo. / Burlarse.",
  1086: "Meter la pata. / Equivocarse.",
  1087: "Estar como una cabra. / Estar loco.",
  1088: "Ser pan comido. / Muy fácil.",
  1089: "Costar un ojo de la cara. / Muy caro.",
  1090: "Llover a cántaros. / Llover mucho.",
  1091: "Estar en el quinto pino. / Muy lejos.",
  1092: "Ser uña y carne. / Muy unidos.",
  1093: "Hablar por los codos. / Hablar mucho.",
  1094: "Estar pez. / No saber nada.",
  1095: "Dar en el clavo. / Acertar.",
  1096: "Estar hecho polvo. / Muy cansado.",
  1097: "Dormir como un tronco. / Dormir profundamente.",
  1098: "Pasarlo pipa. / Divertirse mucho.",
  1099: "Ver las estrellas. / Sentir mucho dolor.",
  1100: "Ser un aguafiestas. / Arruinar la diversión.",
  1101: "Tener mano izquierda. / Ser diplomático.",
  1102: "Hacer castillos en el aire. / Soñar despierto.",
  1103: "La gota que colma el vaso. / El límite.",
  1104: "Pedir peras al olmo. / Pedir lo imposible.",
  1105: "Buscar una aguja en un pajar. / Muy difícil de encontrar.",
  1106: "Estar hasta las narices. / Estar harto.",
  1107: "Importar un pimiento. / No importar nada.",
  1108: "Montar un pollo. / Hacer un escándalo.",
  1109: "Tener mala leche. / Mal carácter.",
  1110: "Ser un trozo de pan. / Muy buena persona.",
  1111: "Echar un cable. / Ayudar.",
  1112: "Ponerse las pilas. / Esforzarse.",
  1113: "Estar sin blanca. / Sin dinero.",
  1114: "Tirar la toalla. / Rendirse.",
  1115: "Hacer la vista gorda. / Ignorar algo.",
  1116: "Quedarse de piedra. / Sorprenderse mucho.",
  1117: "Estar en la luna. / Distraído.",
  1118: "Tener pájaros en la cabeza. / Ideas locas.",
  1119: "Ser un cero a la izquierda. / No valer nada.",
  1120: "Dar la lata. / Molestar.",
  1121: "Estar como pez en el agua. / Muy cómodo.",
  1122: "Tener la sartén por el mango. / Tener el control.",
  1123: "Estar en el ajo. / Estar al tanto.",
  1124: "Dar gato por liebre. / Engañar.",
  1125: "Hacer la pelota. / Adular.",
  1126: "Tener un as en la manga. / Tener un plan secreto.",
  1127: "Estar en el candelero. / Ser famoso.",
  1128: "Dar la vuelta a la tortilla. / Cambiar la situación.",
  1129: "Estar entre la espada y la pared. / En una situación difícil.",
  1130: "Hacer oídos sordos. / Ignorar.",
  1131: "Tener la mosca detrás de la oreja. / Sospechar.",
  1132: "Estar con el agua al cuello. / En apuros.",
  1133: "Dar largas. / Posponer.",
  1134: "Estar en las últimas. / Casi acabado.",
  1135: "Hacer la vista gorda. / Fingir no ver.",
  1136: "Tener malas pulgas. / Mal genio.",
  1137: "Estar en la cuerda floja. / Situación peligrosa.",
  1138: "Dar calabazas. / Rechazar.",
  1139: "Estar en el séptimo cielo. / Muy feliz.",
  1140: "Hacer de menos. / Despreciar.",
  1141: "Tener el santo de espaldas. / Mala suerte.",
  1142: "Estar en babia. / Distraído.",
  1143: "Dar la nota. / Llamar la atención.",
  1144: "Estar en ascuas. / Nervioso.",
  1145: "Hacer la cama. / Conspirar contra alguien.",
  1146: "Tener vista de lince. / Muy buena vista.",
  1147: "Estar en danza. / Ocupado.",
  1148: "Dar la cara. / Asumir responsabilidad.",
  1149: "Estar en vilo. / Intranquilo.",
  1150: "Hacer leña del árbol caído. / Aprovecharse.",
  1151: "Tener correa. / Ser paciente.",
  1152: "Estar en veremos. / Incierto.",
  1153: "Dar la espalda. / Abandonar.",
  1154: "Estar en capilla. / Esperando algo malo.",
  1155: "Hacer borrón y cuenta nueva. / Empezar de cero.",
  1156: "Tener ángel. / Ser carismático.",
  1157: "Estar en la brecha. / Luchando.",
  1158: "Dar la talla. / Estar a la altura.",
  1159: "Estar en la pomada. / Estar al tanto.",
  1160: "Hacer buenas migas. / Llevarse bien.",
  1161: "Tener gancho. / Ser atractivo.",
  1162: "Estar en la cresta de la ola. / En el mejor momento.",
  1163: "Dar la campanada. / Sorprender.",
  1164: "Estar en la inopia. / Despistado.",
  1165: "Hacer el paripé. / Fingir.",
  1166: "Tener tablas. / Experiencia.",
  1167: "Estar en la picota. / Ser criticado.",
  1168: "Dar la murga. / Molestar.",
  1169: "Estar en la luna de Valencia. / Distraído.",
  1170: "Hacer el agosto. / Ganar mucho dinero.",
  1171: "Tener duende. / Tener encanto.",
  1172: "Estar en la higuera. / Despistado.",
  1173: "Dar la matraca. / Insistir mucho.",
  1174: "Estar en la parra. / Distraído.",
  1175: "Hacer el primo. / Ser ingenuo.",
  1176: "Tener salero. / Tener gracia.",
  1177: "Estar en las nubes de algodón. / Muy distraído.",
  1178: "Dar la tabarra. / Molestar.",
  1179: "Estar en Belén. / Despistado.",
  1180: "Hacer el canelo. / Hacer el ridículo.",
  1181: "Tener morro. / Ser descarado.",
  1182: "Estar en la edad del pavo. / Adolescencia.",
  1183: "Dar la brasa. / Molestar.",
  1184: "Estar en la gloria. / Muy feliz.",
  1185: "Hacer el indio. / Hacer tonterías.",
  1186: "Tener cara. / Ser descarado.",
  1187: "Estar en la onda. / Estar actualizado.",
  1188: "Dar la lata. / Molestar.",
  1189: "Estar en la ruina. / Sin dinero.",
  1190: "Hacer el tonto. / Actuar tontamente.",
  1191: "Tener jeta. / Ser descarado.",
  1192: "Estar en la miseria. / Muy pobre.",
  1193: "Dar la vara. / Molestar.",
  1194: "Estar en la indigencia. / Muy pobre.",
  1195: "Hacer el ridículo. / Quedar mal.",
  1196: "Tener labia. / Hablar bien.",
  1197: "Estar en la penuria. / Pasando necesidades.",
  1198: "Dar la paliza. / Molestar mucho.",
  1199: "Estar en la miseria. / Muy pobre.",
  1200: "Hacer el ganso. / Hacer tonterías."
};

try {
  console.log(`Reading file from ${path}...`);
  const data = JSON.parse(fs.readFileSync(path, 'utf8'));
  let updatedCount = 0;

  data.forEach(item => {
    if (translations[item.id]) {
      item.spanish = translations[item.id];
      updatedCount++;
    }
  });

  console.log(`Writing file...`);
  fs.writeFileSync(path, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Successfully updated ${updatedCount} records with Spanish translations.`);
} catch (error) {
  console.error('Error updating file:', error);
}
